# Generated by Django 4.2 on 2024-11-15 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('required_skills', models.CharField(max_length=200)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=200)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('applied_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='jobpostings.jobposting')),
            ],
        ),
    ]
