# Generated by Django 4.2 on 2024-11-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpostings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='posted_on',
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='required_skills',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Applicant',
        ),
    ]
