# Generated by Django 4.2 on 2024-11-25 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobpostings', '0005_alter_jobposting_experience_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('skills', models.TextField()),
                ('experience', models.IntegerField()),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='jobpostings.jobposting')),
            ],
        ),
    ]
